version: '3.8'

services:
  nest-app:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres_user
      DATABASE_PASSWORD: postgres_password
      DATABASE_DB: my_database
    depends_on:
      - postgres
    command: sh -c 'yarn start:prod'

  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: my_database
    ports:
      - '5433:5432'
