name: Deplot to server
on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        env:
          SERVER_HOST: ${{secrets.SERVER_HOST}}
          SERVER_USER: ${{secrets.SERVER_USER}}
          SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          echo "$SSH_KEY" > my_ssh_key.pem
          chmod 600 my_ssh_key.pem
          ssh -i my_ssh_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST '
          cd /home/ubuntu/app/1-loyiha
          git pull origin main
          docker compose down
          docker compose up -d --build'
